### ISSUE TITLE
How to Implement Vast or VPAID ad codes?

### ISSUE THREAD

**Issue by Crssp** [baqarrivi/VideoJs-wordpress-plugin-with-Vast-IMA#1]
Is there any documentation on how to implement ad codes, was it ever implemented in the plugin.
Not sure I see how to use the IMA SDK to place ads either in admin, or how to code it?

I just discovered an official Google getting started guide here, and apologize for being a newbie:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/quickstart

Also will the Readme ever be filled in, curious if this github project is a branch of any other github projects, officially or un-officiallly?

Thanks.
crssp

**Comment by syedbaqarrizvi** [comment]
Hello Crssp,
You need to add your IMA Tag into the code, may i know what ad publishing service you are using, if you still have any questions please feel free to ask and sorry for late reply ,
Thanks 
Baqar
